"""Reproducible ingestion entry point.

    cd backend
    python -m app.ingestion.run              # validate + ingest + write output
    python -m app.ingestion.run --check      # validate only, write nothing

Reads the raw dataset, validates the knowledge base against it, normalizes every
course and writes a JSON file for the future database seed. The raw CSV is opened
read-only and never written to.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT / "backend") not in sys.path:  # allow `python app/ingestion/run.py` too
    sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.ingestion.coursera import coverage_report, ingest, read_rows  # noqa: E402
from app.ingestion.coursera import dataset_vocabulary  # noqa: E402
from app.knowledge.loader import (  # noqa: E402
    KnowledgeBaseError,
    load_knowledge_base,
    validate_against_dataset,
)

DATASET = REPO_ROOT / "data" / "coursera_course_dataset_v3.csv"
OUTPUT = REPO_ROOT / "data" / "processed" / "courses.normalized.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Ingest and normalize the Coursera dataset.")
    parser.add_argument("--dataset", type=Path, default=DATASET)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="validate only, write no output")
    args = parser.parse_args(argv)

    if not args.dataset.exists():
        print(f"dataset not found: {args.dataset}", file=sys.stderr)
        return 1

    # ---- validate the knowledge base ------------------------------------
    try:
        kb = load_knowledge_base()
    except KnowledgeBaseError as error:
        print("Knowledge base validation FAILED\n", file=sys.stderr)
        print(error, file=sys.stderr)
        return 1

    vocabulary = dataset_vocabulary(read_rows(args.dataset))
    alias_problems = validate_against_dataset(kb, vocabulary)
    if alias_problems:
        print("Alias validation FAILED\n", file=sys.stderr)
        for problem in alias_problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print("Knowledge base valid")
    print(f"  skills            {len(kb.skills)}")
    print(f"  careers           {len(kb.careers)}")
    print(f"  aliases           {len(kb.alias_map)}")
    print(f"  out of scope      {len(kb.out_of_scope_skills)}")
    print(f"  dataset vocab     {len(vocabulary)} raw skill strings, fully accounted for")

    # ---- ingest ----------------------------------------------------------
    result = ingest(args.dataset, kb)
    coverage = coverage_report(result, kb)

    total_skill_assignments = sum(len(c.skills) for c in result.courses)
    raw_skill_assignments = sum(len(c.raw_skills) for c in result.courses)
    with_tech = result.courses_with_technical_skills
    without_tech = result.courses_without_technical_skills

    print("\nIngestion")
    print(f"  total courses                     {len(result.courses)}")
    print(f"  raw skill assignments             {raw_skill_assignments}")
    print(f"  normalized skill assignments      {total_skill_assignments}")
    print(f"  distinct canonical skills used    {len(result.skill_course_counts)} / {len(kb.skills)}")
    print(f"  unmapped raw skill strings        {len(result.unmapped_skill_counts)} "
          f"({sum(result.unmapped_skill_counts.values())} assignments, dropped by design)")
    print(f"  courses with technical skills     {len(with_tech)}")
    print(f"  courses without technical skills  {len(without_tech)}")
    print(f"  courses with a URL                {sum(1 for c in result.courses if c.url)}")

    no_coverage = sorted(s for s, c in coverage.items() if c["coverage"] == "none")
    proxy_only = sorted(s for s, c in coverage.items() if c["coverage"] == "proxy")
    thin = sorted(s for s, c in coverage.items() if c["coverage"] == "thin")
    print(f"\n  skills with good coverage         {sum(1 for c in coverage.values() if c['coverage'] == 'good')}")
    print(f"  skills with thin coverage         {len(thin)}  {thin}")
    print(f"  skills with proxy coverage only   {len(proxy_only)}  {proxy_only}")
    print(f"  skills with no coverage           {len(no_coverage)}  {no_coverage}")

    if args.check:
        print("\n--check: no output written")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source_file": args.dataset.name,
        "course_count": len(result.courses),
        "skill_taxonomy_version": 1,
        "notes": [
            "Generated by backend/app/ingestion/run.py. Do not edit by hand.",
            "course_description is display-only and untrusted; the audit found rows "
            "carrying another course's text. Recommendation logic must not read it.",
            "review_count_is_approximate marks values the source stored as e.g. '20K'.",
        ],
        "counts": {
            "courses": len(result.courses),
            "courses_with_technical_skills": len(with_tech),
            "courses_without_technical_skills": len(without_tech),
            "courses_with_url": sum(1 for c in result.courses if c.url),
            "raw_skill_assignments": raw_skill_assignments,
            "normalized_skill_assignments": total_skill_assignments,
            "unmapped_skill_strings": len(result.unmapped_skill_counts),
        },
        "skill_coverage": coverage,
        "unmapped_skills": dict(result.unmapped_skill_counts.most_common()),
        "courses": [asdict(course) for course in result.courses],
    }
    with args.output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    print(f"\nWrote {args.output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
